### ISSUE TITLE
which data is the "mesh over-segmentation results"  and "graphs"  in the step-2?

### ISSUE THREAD

**Issue by titlezi** [WeixiaoGao/PSSNet#1]
Hi author:
your work is really nice!
In the step-2, I don't understand which data is "mesh over-segmentation results" , I try to use `segments_pnp` and it failed. 
Does "mesh over-segmentation results"  mean the `feature_pnp`, and  "graphs" mean `spg_inputs/graphs_edges`?

Yours!
Best regards!
Tian

**Comment by WeixiaoGao** [comment]
Hi Tian,

Thank you for your interest in our project. 
We generate mesh over-segmentation results only in step-1. You can simply run `PSSNet_pipeline_for_GCN` in step-1 to generate all data for step-2.
In step-2, we do not do the mesh over-segmentation, but we perform the GCN-based semantic segmentation. The input for step-2 should be in the folder `spg_input`. You can simply copy the data in `spg_input/pcl/` to `../datasets/custom_set/data/` and the data in `spg_input/graph_edges/` to `../datasets/custom_set/pssnet_graphs/`. The data in `segments_pnp` is only for visualization. The mesh over-segmentation results for step-2 are encoded in the data in `spg_input/pcl/`, and the graph is encoded in the data in `spg_input/graph_edges/`. Int step-2, we just use the `pssnet_partition.py` to convert from *.ply to *.h5 for later processing in `pssnet_main.py`.

Kind regards,
Gao

**Comment by titlezi** [comment]
> Hi Tian,
> 
> Thank you for your interest in our project. We generate mesh over-segmentation results only in step-1. You can simply run `PSSNet_pipeline_for_GCN` in step-1 to generate all data for step-2. In step-2, we do not do the mesh over-segmentation, but we perform the GCN-based semantic segmentation. The input for step-2 should be in the folder `spg_input`. You can simply copy the data in `spg_input/pcl/` to `../datasets/custom_set/data/` and the data in `spg_input/graph_edges/` to `../datasets/custom_set/pssnet_graphs/`. The data in `segments_pnp` is only for visualization. The mesh over-segmentation results for step-2 are encoded in the data in `spg_input/pcl/`, and the graph is encoded in the data in `spg_input/graph_edges/`. Int step-2, we just use the `pssnet_partition.py` to convert from *.ply to *.h5 for later processing in `pssnet_main.py`.
> 
> Kind regards, Gao

Thanks for your reply. 
Best regards!
Tian
