### ISSUE TITLE
Visualisation of step2

### ISSUE THREAD

**Issue by HanyuanYU** [WeixiaoGao/PSSNet#11]
I want to visualise the results of step2, but only pcl point cloud data has been generated, how can I get a mesh visualisation of the results?
The organization of the data in the folders:
![屏幕截图 2024-10-26 192240](https://github.com/user-attachments/assets/75e56607-12a2-4bde-95bd-b85fe2897428)
Results generated by running partition/pssnet_visualize.py:
![屏幕截图 2024-10-26 191838](https://github.com/user-attachments/assets/650b60ef-cfb2-421c-a417-ea1b8ce9c23d)
_pcl_gcn_pred_up.ply:
![屏幕截图 2024-10-26 191918](https://github.com/user-attachments/assets/58712b30-5218-4048-aad7-7ab7307aa3ef)
_pcl_gcn_err.ply:
![屏幕截图 2024-10-26 191945](https://github.com/user-attachments/assets/c5a89bcb-bd48-4dab-af9f-39e8bcdefd8a)
Looking forward to your help!

**Comment by WeixiaoGao** [comment]
Hi, you need to use the '[Evaluation_SOTA](https://github.com/tudelft3d/PSSNet/tree/main/step-1#:~:text=to%20the%20GCN.-,Evaluation_SOTA,-%3A%20Transferring%20the%20semantic)' in step-1 to do this.

**Comment by HanyuanYU** [comment]
Thank you！
