### ISSUE TITLE
can't open "trained_model.gz"

### ISSUE THREAD

**Issue by JurinJC** [WeixiaoGao/PSSNet#3]
Hi author:
I have some problems with the data. 
I have download the model "trained_model.gz", but i cant open it. Is it wrong data? 
Would you provide the test data?

Yours!
Best regards!
Jurin

**Comment by WeixiaoGao** [comment]
Hi, '*.gz' is the trained model for planar and non-planar classification, and please refer to [here](https://github.com/tudelft3d/SUMS-Semantic-Urban-Mesh-Segmentation-public/issues/1) for more information. As for the data, you can find it from [SUM](https://3d.bk.tudelft.nl/projects/meshannotation/#:~:text=Data%20Download-,The,-mesh%20data%20can).

**Comment by JurinJC** [comment]
Thanks！
