### ISSUE TITLE
What is the true dataset of step2?

### ISSUE THREAD

**Issue by JurinJC** [WeixiaoGao/PSSNet#4]
Hi author:
In step2, if I must train the network? Does all the inputs of step2 generated from step1(train test and predictions)?

Yours!
Best regards!
Jurin

**Comment by WeixiaoGao** [comment]
Please refer to [here](https://github.com/tudelft3d/PSSNet/issues/1#issuecomment-1499629946) on how to perform the step-2. And you can download the pre-trained model from [here](https://surfdrive.surf.nl/files/index.php/s/h9w1dkdEDA45Q2V).

**Comment by SpikeXCZ** [comment]
I have similar question that what folders should I build for step2, and where should I put the over-seg results in? I'm confused about the readme command "--dataset custom_dataset --ROOT_PATH $CUSTOM_SET_DIR", i didn't get any  "custom**" named files in step1...

**Comment by WeixiaoGao** [comment]
You need to create two folders to store the results of step 1: `../datasets/custom_set/data/` and `../datasets/custom_set/pssnet_graphs/`. The remaining folders will be created automatically. Please refer to the above reply for more information on where to place the over-segmentation results. You can ignore "custom_dataset" as we don't really use it at this stage to differentiate between other datasets.

**Comment by JurinJC** [comment]
> Please refer to [here](https://github.com/tudelft3d/PSSNet/issues/1#issuecomment-1499629946) on how to perform the step-2. And you can download the pre-trained model from [here](https://surfdrive.surf.nl/files/index.php/s/h9w1dkdEDA45Q2V).

But I can't find the train data for step2.

**Comment by WeixiaoGao** [comment]
The training data for step 2 can be generated in step 1, and the size of the data can be very large.

**Comment by JurinJC** [comment]
I have run the step1 with the mode(PSSNet pipeline for GCN), the result of test&validate(in pssnet_graphs/pcl) can be generated,  but I still can't get the train data for step2, and teh trained model generated from step1 is very small.  ![企业微信截图_16923441511813](https://github.com/tudelft3d/PSSNet/assets/141813222/317be0d2-e0db-4bd1-899d-83a6391d6494) [
![企业微信截图_16923445215814](https://github.com/tudelft3d/PSSNet/assets/141813222/76e064b3-51b1-498b-b24b-02fa7a314df5)
](url)

**Comment by WeixiaoGao** [comment]
Hi, thanks for pointing out this issue. I have fixed this small bug in the "dev" branch and created a PR. You can update the project and use 'dev' to get the training data for step2.

**Comment by JurinJC** [comment]
if I only want to run my predict data using your model of step2, can I only run **python partition/pssnet_visualize.py --dataset custom_dataset --ROOT_PATH $CUSTOM_SET_DIR --res_file "../datasets/custom_set/results/predictions_test" --output_type r**?  Also what is the res_file(predictions_test.h5), I don't have this file.

**Comment by WeixiaoGao** [comment]
`pssnet_visualize.py` is only used to write visualization results. Running your prediction data is similar to running the test data like [here](https://github.com/tudelft3d/PSSNet/tree/dev/step-2#learning). For the trained model and other related files,see [here](https://github.com/tudelft3d/PSSNet/tree/dev/step-2#learning).

**Comment by JurinJC** [comment]
When I run the test data like the example, I got an error like this:
![image](https://github.com/tudelft3d/PSSNet/assets/141813222/bc2d5e6c-2f8e-4547-af04-49972193508b)
I can't fix it. Is this error related to the torch version? What is your torch version

**Comment by WeixiaoGao** [comment]
Hi, I am using Pytorch 1.12 if I remember correctly, but I don't think this is related to the Pytorch version. The parameters of the training model don't seem to match the current code. I'm not sure what is causing this, maybe it's because of the new data. Can you try to retrain the model or test it on the SUM dataset?

**Comment by JurinJC** [comment]
Hi, actually I use the SUM dataset you provided
![image](https://github.com/tudelft3d/PSSNet/assets/141813222/67ca4d4d-2303-4394-a782-4d21ab1f7956)
they are generated from step1

**Comment by JurinJC** [comment]
When I retrain the model using the SUM dataset, I got an error again, like this: 
![企业微信截图_16929375111141](https://github.com/tudelft3d/PSSNet/assets/141813222/35817de0-2685-4cb2-84da-a23262454e48)
![企业微信截图_16929375499678](https://github.com/tudelft3d/PSSNet/assets/141813222/8349e02a-1647-4d62-929d-e986706e966f)
When I load the .h5 files, I cant find where the parameter **"entry"** comes from, what **" G.vs[s]['v']"** actually is.

**Comment by JurinJC** [comment]
cloud, add_feas = load_superpoint(args, db_path + '/features/' + fname + '.h5', G.vs[s]['v'], train, test_seed_offset, s_label)

**Comment by JurinJC** [comment]
In this code: 
```python
cloud, add_feas = load_superpoint(args, db_path + '/features/' + fname + '.h5', G.vs[s]['v'], train, test_seed_offset, s_label)
``` 
yours is "/parsed/", I dont have this folder, so I change it to '/features/'.

**Comment by WeixiaoGao** [comment]
Please do not change any of the names of the folders as this will cause unexpected errors. You do not have "/parsed/" because you did not run the preprocessing step to generate them.  You need to run the [pssnet_custom_dataset.py](https://github.com/tudelft3d/PSSNet/blob/main/step-2/learning/pssnet_custom_dataset.py) to generate the "/parsed/" folder before you run the [pssnet_main.py](https://github.com/tudelft3d/PSSNet/blob/main/step-2/learning/pssnet_main.py). Don't forget to run [pssnet_partition.py](https://github.com/tudelft3d/PSSNet/blob/main/step-2/partition/pssnet_partition.py) to generate '/features/' at first. So the pipeline is [pssnet_partition.py](https://github.com/tudelft3d/PSSNet/blob/main/step-2/partition/pssnet_partition.py) -> [pssnet_custom_dataset.py](https://github.com/tudelft3d/PSSNet/blob/main/step-2/learning/pssnet_custom_dataset.py) ->  [pssnet_main.py](https://github.com/tudelft3d/PSSNet/blob/main/step-2/learning/pssnet_main.py) -> [pssnet_visualize.py](https://github.com/tudelft3d/PSSNet/blob/main/step-2/partition/pssnet_visualize.py).

**Comment by JurinJC** [comment]
When I run only predict data with **operating_mode = PSSNet_pipeline_for_GCN**, I can only get result like this 
![企业微信截图_16933147745894](https://github.com/tudelft3d/PSSNet/assets/141813222/e045b88e-c207-4359-ae8c-edfd48192f21)
this is the classifaction
![企业微信截图_16933149582773](https://github.com/tudelft3d/PSSNet/assets/141813222/74dc60e8-1b0e-4230-bbbb-8e41774a0da2)
this is mesh_seg in segments
![企业微信截图_16933150116386](https://github.com/tudelft3d/PSSNet/assets/141813222/f61c6156-a79d-4569-9b0a-70c001a83c70)
I can't run PSSNet_oversegmentation and subsequent operations, so I cant get the predict dataset for step2.

**Comment by WeixiaoGao** [comment]
Have you updated your code and switched to the `dev` branch? The current `main` branch contains bugs that will be merged by `dev` after the updated code has been reviewed.

**Comment by JurinJC** [comment]
I have switched to dev branch. However, when I load trained model, I always got something error.

**Comment by WeixiaoGao** [comment]
Could you provide more information about the error?

**Comment by JurinJC** [comment]
Thank for your help, I have done the hole code, but my result is very bad, can you give my some help? （used my own data）
This is the input mesh:
![企业微信截图_16940781989441](https://github.com/tudelft3d/PSSNet/assets/141813222/f08220e9-84e5-4c8c-8792-9159484b7ac5)

This is the result of step1:
![企业微信截图_16940782492385](https://github.com/tudelft3d/PSSNet/assets/141813222/2a931d89-2be2-41ff-b161-27a54e20f63a)

This is the seg result:
![企业微信截图_16940782961517](https://github.com/tudelft3d/PSSNet/assets/141813222/9e6fd9e0-ba54-4333-bf1a-843e43e8ea37)

**Comment by WeixiaoGao** [comment]
Hi, it seems your mesh contains topological errors such as duplicated or non-manifold vertices, which could lead to bad results. These errors can break the continuity of the mesh surface and can be difficult to fix, especially if the vertices are related to texture coordinates.

**Comment by JurinJC** [comment]
I have run your dataset but the result of step1 is not very well
This is  the segment_pnp
![企业微信截图_16943944881461](https://github.com/tudelft3d/PSSNet/assets/141813222/cc46a9e8-0b2e-4c44-95a1-43c3bddd46d4)
This is the truth
![企业微信截图_16943945006120](https://github.com/tudelft3d/PSSNet/assets/141813222/c6c7540a-4b4d-49b1-bd10-7cf9b1be0d07)

**Comment by JurinJC** [comment]
I have fix the input, but the result is bad too, can you give me some advice?
![企业微信截图_16943983892727](https://github.com/tudelft3d/PSSNet/assets/141813222/1f1bee40-56d0-4ad7-8405-ea75579d4980)
![企业微信截图_16943984077102](https://github.com/tudelft3d/PSSNet/assets/141813222/dfff1058-4a54-4419-8b6c-b6b9d9a8cded)
![企业微信截图_16943984145631](https://github.com/tudelft3d/PSSNet/assets/141813222/a007ae62-469c-4126-a8b7-39ba4e8ba299)

**Comment by WeixiaoGao** [comment]
For me, this result is better than your previous one. You can further fine tune the "balance parameter" to get better results on your dataset.
However, from your second image, the classification of planar and non-planar is not as good as expected. I guess you are not using colour information?

**Comment by JurinJC** [comment]
Thanks for your answer. Actually I have used the texture, so I think I also used the colour information.

**Comment by WeixiaoGao** [comment]
If you use our pre-trained model on your data, the results for planar and non-planar classification are acceptable because of the significant domain gap between your data and our benchmark dataset.
