### ISSUE TITLE
Step1 make failed

### ISSUE THREAD

**Issue by SpikeXCZ** [WeixiaoGao/PSSNet#6]
Hi, Dr.Gao
My CMake all good, but run "make" and get these report: 
![2023-08-18 17-38-33](https://github.com/tudelft3d/PSSNet/assets/142301609/a9a3f568-581c-4555-9b90-a64609caaaa6)

Looking forward your help~
Thank you!

**Comment by WeixiaoGao** [comment]
Hi, as mentioned in the [ReadMe](https://github.com/tudelft3d/PSSNet/tree/main/step-1#usage), compiling step-1 on Ubuntu is not supported. If you want to do so, you need to modify the code and replace the current 'filesystem' to boost the filesystem.

**Comment by Roy2xc** [comment]
Thank you Dr.GAO ！
By your tip I successfully compiled on Win10. Now I am trying to test my own data using the model you provided. I don't need training, and just want to try the effect. How should I modify config.txt?
Here is my config:
![cut](https://github.com/tudelft3d/PSSNet/assets/42893773/0714bcbc-c4ff-49ee-b9ce-aec51ec655b1)

**Comment by SpikeXCZ** [comment]
Thank you Dr.GAO!
By your tip I successfully compiled on Win10. Now I am trying to test my own data using the model you provided. I don't need training, I just want to try the effect. How should I modify config.txt?
Here is my Config.txt:
![cut](https://github.com/tudelft3d/PSSNet/assets/142301609/190b11ad-d58a-4f97-9f96-92e316333493)

**Comment by WeixiaoGao** [comment]
You can enable the `process_predict = true` and disable others, then put all your data in predict folder and run the same pipeline. But there is no guarantee that you can get correct results as meshes can be very different from one to another.

**Comment by SpikeXCZ** [comment]
Hi, Dr.GAO:
The predict is all good and I got a set of over-seg mesh, but I did not get data in spg_input/pcl/  and the data in spg_input/graph_edges,  which means I may be not able to run step2... How to get spg-like data? 
Here is my over-seg result
![7](https://github.com/tudelft3d/PSSNet/assets/142301609/8ebe1114-abcc-4423-9356-daa0c1444712)

**Comment by WeixiaoGao** [comment]
Hello, I've fixed a small bug with reading predicted data in the `dev` branch and you should be able to generate predicted data for step 2. Please note that you need to create the `predict` folder in a different directory in advance. Also, the quality of your over-segmented results doesn't seem to be very good, especially on the non-planar segments, which should be merged into one larger segment. One possible reason for this is that the input texture image is missing.

**Comment by SpikeXCZ** [comment]
Thank you!  But there is still nothing generated in spg_input or  spg_out...  Should I change the mode? I'm using PSSNet_pipeline_for_GCN, it seems not work because including training and testing part And if I changed it into PSSNet_oversegmentation, It will ask me for XXX_mesh_classification.ply which is not generated.

Looking forward to your help~

**Comment by WeixiaoGao** [comment]
Did you switch to the `dev` branch and update the code? Please check the commit history to see if there are any matched changes in the local repository.

**Comment by SpikeXCZ** [comment]
Yes, I did. It seems stuck after finishing "pipline" part. And I can get over-seg results, but cannot find spg stuff.

**Comment by WeixiaoGao** [comment]
I just tested it this morning and it works fine, so I guess there must be something wrong with your configuration, local directory or input data. Can you try using the SUM data as predictive data to see if it works? Can you also provide more information on what it's stuck on (e.g., the prints from the program)?

**Comment by JurinJC** [comment]
> One possible reason for this is that the input texture image is missing

If I don't have the texture, does the segment result will be bad?

**Comment by WeixiaoGao** [comment]
Yes, the results can be worse, but the most of planar segments can be detected.

**Comment by JurinJC** [comment]
What does the texture do? Color properties? Can I use the rgb mesh install of  the mesh with texture?

**Comment by WeixiaoGao** [comment]
Color information is used for over-segmentation and semantic segmentation. I don't understand what RGB mesh you are referring to here, do you mean a mesh with face colors? If so, you can use it to replace the original texture. But you may need to modify the source code.

**Comment by JurinJC** [comment]
Yes, the rgb mesh I mentioned before is the face color. So, the effect of texture is providing color information used for over-segmentation and semantic segmentation, right?
